FROM golang:1.19

RUN echo "Asia/Shanghai" >> /etc/timezone
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV GOPROXY https://goproxy.cn

#声明build-args变量，demo_project是默认值
COPY ./realtime-consumption/src /go/src
WORKDIR /go/src/myapp
RUN CGO_ENABLED=0 GOOS=linux go build -o main
ENTRYPOINT ./main
